# Generated by Django 5.1.4 on 2026-04-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='BookOpen', max_length=64)),
                ('color', models.CharField(default='from-blue-500 to-cyan-600', max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('section_title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='English', max_length=64)),
                ('level', models.CharField(default='Beginner', max_length=64)),
                ('prep_questions', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.collection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
